# Generated by Django 6.0.5 on 2026-08-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='products/')),
                ('nomi', models.CharField(max_length=50)),
                ('narxi', models.IntegerField()),
                ('skidka', models.IntegerField(blank=True, default=0)),
                ('rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_aksiya', models.BooleanField(default=False)),
                ('is_arzonlashdi', models.BooleanField(default=False)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Uzum.category')),
            ],
        ),
    ]
