# Generated by Django 6.0.5 on 2026-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='rasm',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='skidka',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='tavsif',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
